"""
Database operations and connection management
"""
import atexit
import logging
from contextlib import contextmanager
from psycopg import connect, Error
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool
from config import DATABASE_URL, DATABASE_TIMEOUT


logger = logging.getLogger(__name__)


DB_POOL_MIN_SIZE = 1
DB_POOL_MAX_SIZE = 10

_db_pool = None


def _get_db_pool():
    """Get or create shared connection pool."""
    global _db_pool
    if _db_pool is None:
        _db_pool = ConnectionPool(
            conninfo=DATABASE_URL,
            min_size=DB_POOL_MIN_SIZE,
            max_size=DB_POOL_MAX_SIZE,
            kwargs={
                'connect_timeout': int(DATABASE_TIMEOUT),
                'row_factory': dict_row,
            },
            open=True,
        )
        logger.info("Initialized PostgreSQL connection pool (%s-%s)", DB_POOL_MIN_SIZE, DB_POOL_MAX_SIZE)
    return _db_pool


def close_db_pool():
    """Close shared connection pool."""
    global _db_pool
    if _db_pool is not None:
        _db_pool.close()
        _db_pool = None
        logger.info("Closed PostgreSQL connection pool")


atexit.register(close_db_pool)


@contextmanager
def get_db_connection():
    """Context manager for database connections"""
    conn = None
    try:
        pool = _get_db_pool()
        with pool.connection() as pooled_conn:
            conn = pooled_conn
            yield conn
            conn.commit()
    except Error as e:
        if conn:
            conn.rollback()
        logger.exception("Database error: %s", e)
        raise


def init_db():
    """Initialize database tables"""
    with get_db_connection() as conn:
        cursor = conn.cursor()
        
        # Table 1: User category selections
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS user_selections (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                session_id TEXT NOT NULL,
                user_group INTEGER DEFAULT 1,
                round INTEGER DEFAULT 1,
                category_1 TEXT,
                category_1_score INTEGER,
                category_2 TEXT,
                category_2_score INTEGER,
                category_3 TEXT,
                category_3_score INTEGER,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        # Table 2: User counter for generating sequential IDs
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS user_counters (
                group_id INTEGER PRIMARY KEY,
                counter INTEGER DEFAULT 0
            )
        ''')
        
        # Initialize counters for all 6 groups if not exists
        for group_id in range(1, 7):
            cursor.execute('''
                INSERT INTO user_counters (group_id, counter) 
                VALUES (%s, 0)
                ON CONFLICT (group_id) DO NOTHING
            ''', (group_id,))
        
        # Table 3: Video watch duration
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS video_watch_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                session_id TEXT NOT NULL,
                user_group INTEGER DEFAULT 1,
                round INTEGER DEFAULT 1,
                video_id TEXT NOT NULL,
                video_title TEXT,
                video_category TEXT,
                video_index INTEGER,
                watch_duration REAL,
                video_total_duration INTEGER,
                completion_rate REAL,
                liked INTEGER,
                comment TEXT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Table 4: Summary page watch duration
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS summary_page_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                session_id TEXT NOT NULL,
                user_group INTEGER DEFAULT 1,
                round INTEGER NOT NULL,
                duration_seconds REAL NOT NULL,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(session_id, round)
            )
        ''')

        def column_exists(table_name: str, column_name: str) -> bool:
            cursor.execute(
                '''
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = %s
                  AND column_name = %s
                LIMIT 1
                ''',
                (table_name, column_name),
            )
            return cursor.fetchone() is not None

        # Migration: Add columns if they don't exist
        if not column_exists('video_watch_log', 'round'):
            cursor.execute("ALTER TABLE video_watch_log ADD COLUMN round INTEGER DEFAULT 1")
            logger.info("Added 'round' column to video_watch_log table")

        if not column_exists('video_watch_log', 'user_group'):
            cursor.execute("ALTER TABLE video_watch_log ADD COLUMN user_group INTEGER DEFAULT 1")
            logger.info("Added 'user_group' column to video_watch_log table")

        if not column_exists('user_selections', 'user_group'):
            cursor.execute("ALTER TABLE user_selections ADD COLUMN user_group INTEGER DEFAULT 1")
            logger.info("Added 'user_group' column to user_selections table")

        if not column_exists('user_selections', 'round'):
            cursor.execute("ALTER TABLE user_selections ADD COLUMN round INTEGER DEFAULT 1")
            logger.info("Added 'round' column to user_selections table")
        
        # Migration: remove historical unique index so repeated watches are stored as separate records
        try:
            cursor.execute("DROP INDEX IF EXISTS idx_unique_video_log")
        except Error as e:
            logger.info("Index drop note: %s", e)


def get_next_user_id(group_number):
    """Generate next sequential user ID for a group
    
    Args:
        group_number: Group number (1-6)
        
    Returns:
        String user ID in format: group_number concatenated with counter (e.g., '1000', '1001', '2000')
    """
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            '''
            INSERT INTO user_counters (group_id, counter)
            VALUES (%s, 1)
            ON CONFLICT (group_id)
            DO UPDATE SET counter = user_counters.counter + 1
            RETURNING counter
            ''',
            (group_number,),
        )
        row = cursor.fetchone()
        current_counter = int(row['counter']) - 1

        # Generate user ID: group_number * 1000 + counter
        user_id = str(group_number * 1000 + current_counter)

        return user_id


def save_category_selection(user_id, session_id, categories, user_group=1, current_round=1):
    """Save user category selection to database
    
    Args:
        user_id: Unique user identifier
        session_id: Unique session identifier
        categories: List of selected categories with preferences
        user_group: User group number (1-6)
        current_round: Current experiment round (1 or 2)
    """
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO user_selections 
            (user_id, session_id, user_group, round, category_1, category_1_score, 
             category_2, category_2_score, category_3, category_3_score)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ''', (
            user_id,
            session_id,
            user_group,
            current_round,
            categories[0]['name'] if len(categories) > 0 else None,
            categories[0]['preference'] if len(categories) > 0 else None,
            categories[1]['name'] if len(categories) > 1 else None,
            categories[1]['preference'] if len(categories) > 1 else None,
            categories[2]['name'] if len(categories) > 2 else None,
            categories[2]['preference'] if len(categories) > 2 else None
        ))


def save_watch_log(user_id, session_id, current_round, video_data, 
                   watch_duration, completion_rate, liked, comment_text, user_group=1):
    """Save video watch log to database
    
    Args:
        user_id: Unique user identifier
        session_id: Unique session identifier
        current_round: Current experiment round (1 or 2)
        video_data: Dictionary with video information
        watch_duration: Total watch duration in seconds
        completion_rate: Percentage of video watched
        liked: Like status (1=like, -1=dislike, 0=neutral)
        comment_text: User comment text
        user_group: User group number (1-6)
    """
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO video_watch_log 
            (user_id, session_id, user_group, round, video_id, video_title, video_category, 
             video_index, watch_duration, video_total_duration, completion_rate, 
             liked, comment)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ''', (
            user_id,
            session_id,
            user_group,
            current_round,
            video_data['video_id'],
            video_data['video_title'],
            video_data['video_category'],
            video_data['video_index'],
            watch_duration,
            video_data['video_total_duration'],
            completion_rate,
            liked,
            comment_text
        ))


def get_session_statistics(session_id, current_round):
    """Get viewing statistics for a session and round
    
    Args:
        session_id: Unique session identifier
        current_round: Current experiment round
        
    Returns:
        List of category statistics
    """
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute('''
             SELECT video_category,
                 COALESCE(SUM(watch_duration), 0) AS total_duration,
                 COUNT(DISTINCT video_id) AS video_count
             FROM video_watch_log
             WHERE session_id = %s AND round = %s
             GROUP BY video_category
        ''', (session_id, current_round))
        
        return cursor.fetchall()


def save_summary_page_duration(user_id, session_id, current_round, duration_seconds, user_group=1):
    """Save watched duration for a summary page.

    Keeps one row per session+round and updates it on repeated saves.
    """
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            '''
            INSERT INTO summary_page_log
            (user_id, session_id, user_group, round, duration_seconds)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (session_id, round)
            DO UPDATE SET
                user_id = EXCLUDED.user_id,
                user_group = EXCLUDED.user_group,
                duration_seconds = EXCLUDED.duration_seconds,
                timestamp = CURRENT_TIMESTAMP
            ''',
            (user_id, session_id, user_group, current_round, duration_seconds),
        )
